 ### create a new Patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "jitesh ka billing account khul gaya",
  "email": "jitsw12@email.com",
  "address": "123 jane street",
  "dateOfBirth": "2000-07-20",
  "registeredDate": "2024-09-24"
}
###