### update the patient
PUT http://localhost:4000/patients/8290ce32-c43e-4247-9086-4017a681c400
Content-Type: application/json

{
  "name": "Jitesh Doe",
  "email": "jitesh.doe2@example.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-06-15"
}

###